CREATE TABLE [dbo].[Patients] (
    [RowId]                      UNIQUEIDENTIFIER CONSTRAINT [DF_Patients_RowId] DEFAULT (newid()) NOT NULL,
    [Title]                      NVARCHAR (255)   NULL,
    [FirstName]                  NVARCHAR (255)   NOT NULL,
    [MiddleName]                 NVARCHAR (255)   NULL,
    [LastName]                   NVARCHAR (255)   NOT NULL,
    [PreferredName]              NVARCHAR (255)   NULL,
    [FamilyHeadRowId]            UNIQUEIDENTIFIER NOT NULL,
    [FamilyMemberType]           NVARCHAR (255)   NULL,
    [RelationToFamilyHead]       NVARCHAR (255)   NULL,
    [BirthDate]                  DATETIME         NULL,
    [Sex]                        NVARCHAR (255)   NULL,
    [CardNo]                     NVARCHAR (255)   NULL,
    [FirstSeen]                  DATETIME         NULL,
    [SendInvoicesToFamilyMember] UNIQUEIDENTIFIER NULL,
    [Address1]                   NVARCHAR (255)   NULL,
    [Province1]                  NVARCHAR (255)   NULL,
    [City1]                      NVARCHAR (255)   NULL,
    [Postcode1]                  NVARCHAR (255)   NULL,
    [Address2]                   NVARCHAR (255)   NULL,
    [Province2]                  NVARCHAR (255)   NULL,
    [City2]                      NVARCHAR (255)   NULL,
    [Postcode2]                  NVARCHAR (255)   NULL,
    [AddressToUse]               NVARCHAR (255)   NULL,
    [HomePhoneNumber]            NVARCHAR (255)   NULL,
    [MobileNumber]               NVARCHAR (255)   NULL,
    [Occupation]                 NVARCHAR (255)   NULL,
    [EmployerName]               NVARCHAR (255)   NULL,
    [WorkPhone]                  NVARCHAR (255)   NULL,
    [Fax]                        NVARCHAR (255)   NULL,
    [EmailAddress]               NVARCHAR (255)   NULL,
    [FamilyDoctor]               NVARCHAR (255)   NULL,
    [FamilyDoctorAddress]        NVARCHAR (255)   NULL,
    [FamilyDoctorPhoneNumber]    NVARCHAR (255)   NULL,
    [IsDeleted]                  BIT              CONSTRAINT [DF_Patients_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedBy]                  NVARCHAR (255)   NULL,
    [CreatedDateTime]            DATETIME         CONSTRAINT [DF_Patients_CreatedDateTime] DEFAULT (getdate()) NULL,
    [UpdatedBy]                  NVARCHAR (255)   NULL,
    [UpdatedDateTime]            DATETIME         CONSTRAINT [DF_Patients_UpdatedDateTime] DEFAULT (getdate()) NULL,
    [Photo]                      VARBINARY (MAX)  NULL,
    [HasHighBloodPressure]       BIT              CONSTRAINT [DF__Patients__HasHig__498EEC8D] DEFAULT ((0)) NOT NULL,
    [HasPacemaker]               BIT              CONSTRAINT [DF__Patients__HasPac__4A8310C6] DEFAULT ((0)) NOT NULL,
    [HasDiabetes]                BIT              CONSTRAINT [DF__Patients__HasDia__4B7734FF] DEFAULT ((0)) NOT NULL,
    [HasHepatitis]               BIT              CONSTRAINT [DF__Patients__HasHep__4C6B5938] DEFAULT ((0)) NOT NULL,
    [HasHeadaches]               BIT              CONSTRAINT [DF__Patients__HasHea__4D5F7D71] DEFAULT ((0)) NOT NULL,
    [HasSurgeries]               BIT              CONSTRAINT [DF__Patients__HasSur__4E53A1AA] DEFAULT ((0)) NOT NULL,
    [HasMetalImplants]           BIT              CONSTRAINT [DF__Patients__HasMet__4F47C5E3] DEFAULT ((0)) NOT NULL,
    [HasFractures]               BIT              CONSTRAINT [DF__Patients__HasFra__503BEA1C] DEFAULT ((0)) NOT NULL,
    [HasNeckPain]                BIT              CONSTRAINT [DF__Patients__HasNec__51300E55] DEFAULT ((0)) NOT NULL,
    [HasBackPain]                BIT              CONSTRAINT [DF__Patients__HasBac__5224328E] DEFAULT ((0)) NOT NULL,
    [HasShoulderElbowHandPain]   BIT              CONSTRAINT [DF__Patients__HasSho__531856C7] DEFAULT ((0)) NOT NULL,
    [HasHipKneeFootPain]         BIT              CONSTRAINT [DF__Patients__HasHip__540C7B00] DEFAULT ((0)) NOT NULL,
    [OtherMedicalConditions]     NVARCHAR (255)   NULL,
    [HealthHistoryNotes]         NVARCHAR (255)   NULL,
    [ReferrerRowId]              UNIQUEIDENTIFIER NULL,
    [UseHeadAddress]             BIT              DEFAULT ((0)) NOT NULL,
    [Source]                     NVARCHAR (10)    NULL,
    [SourceFullName]             NVARCHAR (255)   NULL,
    CONSTRAINT [PK_Patients] PRIMARY KEY CLUSTERED ([RowId] ASC),
    CONSTRAINT [FK_Patients_Patients] FOREIGN KEY ([FamilyHeadRowId]) REFERENCES [dbo].[Patients] ([RowId]),
    CONSTRAINT [FK_Patients_ReferrerRowId] FOREIGN KEY ([ReferrerRowId]) REFERENCES [dbo].[Referrers] ([RowId])
);

