CREATE TABLE [dbo].[ztest001] (
    [v1]  BIGINT             NULL,
    [v2]  NUMERIC (18)       NULL,
    [v3]  BIT                NULL,
    [v4]  SMALLINT           NULL,
    [v5]  DECIMAL (18)       NULL,
    [v6]  SMALLMONEY         NULL,
    [v7]  INT                NULL,
    [v8]  TINYINT            NULL,
    [v9]  MONEY              NULL,
    [v10] FLOAT (53)         NULL,
    [v11] REAL               NULL,
    [v12] DATE               NULL,
    [v13] DATETIMEOFFSET (7) NULL,
    [v14] DATETIME2 (7)      NULL,
    [v15] SMALLDATETIME      NULL,
    [v16] DATETIME           NULL,
    [v17] TIME (7)           NULL,
    [v18] CHAR (1)           NULL,
    [v19] VARCHAR (1)        NULL,
    [v20] TEXT               NULL,
    [v21] NCHAR (1)          NULL,
    [v22] NVARCHAR (1)       NULL,
    [v23] NTEXT              NULL,
    [v24] BINARY (1)         NULL,
    [v25] VARBINARY (1)      NULL,
    [v26] IMAGE              NULL,
    [v27] ROWVERSION         NOT NULL,
    [v28] UNIQUEIDENTIFIER   NULL,
    [v29] XML                NULL
);

