// Decompiled with JetBrains decompiler
// Type: DevExpress.Xpf.Grid.Themes.GroupRowThemeKeys
// Assembly: DevExpress.Xpf.Grid.v16.1, Version=16.1.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a
// MVID: BB681040-0474-4C7D-BB3E-E6E5DFDDD1F8
// Assembly location: H:\DOWNLOADS\T145231\T145231\bin\Debug\DevExpress.Xpf.Grid.v16.1.dll

using DevExpress.Xpf.Utils.Themes;

namespace DevExpress.Xpf.Grid.Themes
{
  public enum GroupRowThemeKeys
  {
    ExpandButtonStyle,
    ExpandButtonTemplate,
    GroupValueTemplate,
    GroupRowTemplate,
    [BlendVisibility(false)] GroupRowsControlTemplate,
    [BlendVisibility(false)] GroupRowControlTemplate,
    GroupRowControlExpanderStyle,
    GroupRowControlContainerTemplate,
    GroupRowControlHeaderContentTemplate,
    GroupRowPresenterStyle,
    [BlendVisibility(false)] GroupRowsControlContainerTemplate,
    GroupRowStyle,
    GroupRowContentTemplate,
    GroupItemsControlStyle,
    GroupValueContentStyle,
    GroupSummaryContentStyle,
    GroupSummaryItemTemplate,
    GroupColumnSummaryItemTemplate,
    GroupColumnSummaryFocusedBorderBrush,
    GroupColumnSummaryControlTemplate,
    GroupBandSummaryControlTemplate,
    ExpandingStoryboard,
    CollapsingStoryboard,
    CardGroupExpandingStoryboard,
    CardGroupCollapsingStoryboard,
    GroupColumnSummaryPadding,
    GroupBandSummaryPadding,
    GroupBandSummaryNormalBorderBrush,
    GroupBandSummaryFocusedBorderBrush,
    GroupBandSummaryNormalBackground,
    GroupBandSummaryFocusedBackground,
    GroupBandSummaryTemplate,
    GroupBandSummaryContentStyle,
    BandedViewGroupSummaryMinHeight,
    GroupDefaultSummaryPadding,
    GroupRowDefaultSummaryPadding,
    ExpandDetailButtonStyle,
    ExpandDetailButtonTemplate,
    GroupFooterRowControlTemplate,
    GroupFooterRowStyle,
    GroupFooterRowTemplate,
    GroupFooterRowContentTemplate,
    GroupFooterSummaryControlTemplate,
    GroupFooterSummaryContentStyle,
    GroupFooterSummaryItemTemplate,
    GroupFooterSummaryContainerTemplate,
    ExpandButtonMargin,
    GroupRowExpandButtonMargin,
    GroupValuePresenterMargin,
    BandedGroupValuePresenterMargin,
    CheckBoxSelectorMargin,
    GroupGridRowHeaderTextBrush,
    GroupRowBackground,
    GroupRowBackgroundFocused,
    GroupRowBackgroundSelected,
    GroupRowLightweightTemplate,
    GroupRowBottomLineThickness,
    GroupRowFontWeight,
    GroupRowForeground,
    GroupRowFocusForeground,
    GroupRowContentMargin,
    GroupRowColumnSummaryBrushes,
    GroupRowDefaultSummaryMargin,
    GroupRowFixedLineSeparatorTemplate,
    GroupRowFocusOffset,
    GroupRowMinHeight,
  }
}
