// Decompiled with JetBrains decompiler
// Type: DevExpress.Xpf.Grid.Themes.TableViewThemeKeys
// Assembly: DevExpress.Xpf.Grid.v16.1, Version=16.1.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a
// MVID: BB681040-0474-4C7D-BB3E-E6E5DFDDD1F8
// Assembly location: H:\DOWNLOADS\T145231\T145231\bin\Debug\DevExpress.Xpf.Grid.v16.1.dll

using DevExpress.Xpf.Utils.Themes;

namespace DevExpress.Xpf.Grid.Themes
{
  public enum TableViewThemeKeys
  {
    [BlendVisibility(false)] ControlTemplate,
    ScrollViewerTemplate,
    DataNavigatorTemplate,
    ButtonNavigationStyle,
    DataNavigatorTextSize,
    DataNavigatorTextBrush,
    DataNavigatorBackground,
    DataNavigatorBackgroundText,
    DataNavigatorBorderMarginText,
    DataNavigatorBorderThickness,
    DataNavigatorBorderBrush,
    DataNavigatorFocusedBackground,
    DataNavigatorDisableBackground,
    UseGroupShadowIndent,
    LeftDataAreaIndent,
    RightDataAreaIndent,
    LeftGroupAreaIndent,
    RightGroupAreaIndent,
    Margin,
    [BlendVisibility(false)] FixedNoneHeadersPanelTemplate,
    [BlendVisibility(false)] FixedNoneDropPanelTemplate,
    [BlendVisibility(false)] FixedLeftNoneDropPanelTemplate,
    [BlendVisibility(false)] FixedRightNoneDropPanelTemplate,
    [BlendVisibility(false)] FixedLeftHeadersPanelTemplate,
    [BlendVisibility(false)] FixedRightHeadersPanelTemplate,
    [BlendVisibility(false)] FixedSummaryTextBlockStyle,
    [BlendVisibility(false)] HeadersTemplate,
    GroupPanelContentTemplate,
    GroupPanelDragTextStyle,
    GroupPanelBorderThickness,
    GroupPanelBorderBrush,
    GroupPanelSeparatorMargin,
    GroupPanelMargin,
    [BlendVisibility(false)] TotalSummaryContainerTemplate,
    [BlendVisibility(false)] PrintRowTemplate,
    [BlendVisibility(false)] PrintGroupRowTemplate,
    [BlendVisibility(false)] PrintGroupFooterTemplate,
    [BlendVisibility(false)] PrintHeaderTemplate,
    [BlendVisibility(false)] PrintFooterTemplate,
    [BlendVisibility(false)] PrintFixedFooterTemplate,
    ColumnChooserTemplate,
    ColumnBandChooserTemplate,
    ColumnChooserDragTextStyle,
    ColumnChooserBackgroundBrush,
    ColumnChooserBorderBrush,
    FixedLineWidth,
    IndicatorWidth,
    ExpandDetailButtonWidth,
    ExpandDetailButtonWidthTouch,
    DetailMargin,
    OuterBorderElementTemplate,
    OuterBorderElementStyle,
    HorizontalScrollbarMargin,
    RowPresenterGridMargin,
    IndicatorMargin,
    DataPresenterTemplate,
    SearchPanelWithoutGroupedPanelMargin,
    SearchPanelWithGroupedPanelMargin,
    SearchPanelBorderBottomBrush,
    SearchPanelBackground,
    SearchPanelMargin,
    SearchPanelWidth,
    SearchPanelTextBoxMinWidth,
    TotalSummaryPanelMargin,
    SearchPanelContentTemplate,
    DefaultPrintStyleBase,
    DefaultPrintHeaderStyle,
    DefaultPrintTotalSummaryStyle,
    DefaultPrintFixedTotalSummaryStyle,
    DefaultPrintGroupRowStyle,
    DefaultPrintGroupFooterStyle,
    DefaultPrintCellStyle,
    DefaultPrintRowIndentStyle,
    GroupPanelSeparatorBrush,
    CheckBoxSelectorColumnWidth,
    EditFormDialogServiceTemplate,
    EditFormItemsPanelTemplate,
    EditFormItemTemplate,
    EditFormContentTemplate,
    EditFormForeground,
    EditFormBackground,
    AnnotationFocusedRowBrush,
    AnnotationErrorBrush,
    AnnotationSearchBrush,
    AnnotationSelectionBrush,
    AnnotationMargin,
  }
}
