//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentRemaindersForProcessed
    {
        public Nullable<System.DateTime> vnow { get; set; }
        public Nullable<System.DateTime> start_remainder { get; set; }
        public System.Guid RowId { get; set; }
        public System.Guid AppointmentRowId { get; set; }
        public int RemainderInMinutes { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public bool IsRemainderEmail { get; set; }
        public bool IsRemainderSms { get; set; }
        public bool IsProcessedEmail { get; set; }
        public Nullable<System.DateTime> ProcessedEmailTime { get; set; }
        public bool IsProcessedSms { get; set; }
        public Nullable<System.DateTime> ProcessedSmsTime { get; set; }
    }
}
