//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentV()
        {
            this.AppointmentRemainders = new HashSet<AppointmentRemainder>();
        }
    
        public System.Guid RowId { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public string Notes { get; set; }
        public System.Guid PatientRowId { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string RefNumber { get; set; }
        public string RefStatus { get; set; }
        public System.Guid AppointmentBookRowId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<System.Guid> ServiceProviderRowId { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.Guid> MedicalServicesOrSupplyRowId { get; set; }
        public string PatientFullName { get; set; }
        public Nullable<System.Guid> InvoiceRowId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.Guid> Status1RowId { get; set; }
        public Nullable<System.Guid> Status2RowId { get; set; }
        public Nullable<System.Guid> InsuranceCoverageRowId { get; set; }
        public Nullable<System.Guid> InsuranceProviderRowId { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.Guid> PolicyOwnerRowId { get; set; }
        public string PolicyOwnerFullName { get; set; }
        public decimal PatientRate { get; set; }
        public bool HasNoCoverage { get; set; }
        public Nullable<System.Guid> AppointmentClinicalNoteRowId { get; set; }
        public Nullable<System.DateTime> PolicyCoverageStartDate { get; set; }
        public Nullable<System.DateTime> PolicyCoverageValidUntil { get; set; }
        public Nullable<System.Guid> InvoiceItemRowId { get; set; }
        public bool IsIgnoreForChargeout { get; set; }
        public bool IsRemainderEmail { get; set; }
        public bool IsRemainderSms { get; set; }
        public string GoogleCalendarEventId { get; set; }
        public Nullable<System.Guid> AppointmentTreatmentNoteRowId { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
        public bool IsEmailWhenRegistered { get; set; }
        public bool IsSmsWhenRegistered { get; set; }
        public Nullable<System.Guid> ConfirmedByPatientRowId { get; set; }
        public Nullable<System.DateTime> ConfirmedTimestamp { get; set; }
        public string ConfirmedIpAddress { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual InvoiceItem InvoiceItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentRemainder> AppointmentRemainders { get; set; }
    }
}
