//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentForm()
        {
            this.AppointmentFormItems = new HashSet<AppointmentFormItem>();
        }
    
        public System.Guid RowId { get; set; }
        public Nullable<System.Guid> FormRowId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> AppointmentRowId { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentFormItem> AppointmentFormItems { get; set; }
        public virtual AppointmentT Appointment { get; set; }
        public virtual Form Form { get; set; }
    }
}
