//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeoutT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChargeoutT()
        {
            this.ChargeoutItems = new HashSet<ChargeoutItem>();
            this.ChargeoutPaycharges = new HashSet<ChargeoutPaycharge>();
            this.ChargeoutRefcharges = new HashSet<ChargeoutRefchargeT>();
            this.EmailCharges = new HashSet<EmailChargeT>();
        }
    
        public System.Guid RowId { get; set; }
        public string ChargeoutType { get; set; }
        public string ChargeoutNumber { get; set; }
        public Nullable<System.DateTime> ChargeoutDate { get; set; }
        public string BillTo { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToCity { get; set; }
        public string BillToProvince { get; set; }
        public string BillToPostCode { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdateBy { get; set; }
        public string PrintTemplate { get; set; }
        public Nullable<System.Guid> ThirdPartyServiceProviderRowId { get; set; }
        public Nullable<System.Guid> Status1RowId { get; set; }
        public Nullable<System.Guid> Status2RowId { get; set; }
        public decimal Rate { get; set; }
        public bool HasNoCoverage { get; set; }
        public Nullable<System.Guid> ServiceProviderRowId { get; set; }
        public System.Guid ChargeoutRecipientRowId { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutItem> ChargeoutItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutPaycharge> ChargeoutPaycharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutRefchargeT> ChargeoutRefcharges { get; set; }
        public virtual ChargeoutStatus ChargeoutStatus { get; set; }
        public virtual ChargeoutStatus ChargeoutStatus1 { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual ThirdPartyServiceProvider ThirdPartyServiceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeT> EmailCharges { get; set; }
        public virtual ChargeoutRecipient ChargeoutRecipient { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ServiceProvider ServiceProvider1 { get; set; }
        public virtual ServiceProvider ServiceProvider2 { get; set; }
    }
}
