//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSendV
    {
        public System.Guid RowId { get; set; }
        public System.DateTime SendDate { get; set; }
        public Nullable<System.Guid> InvoiceRowId { get; set; }
        public bool IsSuccess { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdateBy { get; set; }
        public string EmailSendRecipientsList { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public string InvoicePatientName { get; set; }
        public Nullable<System.Guid> InvoicePatientRowId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    }
}
