//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePatientCategory2InsuranceArticleV
    {
        public System.Guid InsuranceCoverageRowId { get; set; }
        public System.Guid PatientRowId { get; set; }
        public System.Guid CategoryRowId { get; set; }
        public bool CoversAllHolders { get; set; }
        public System.Guid InsuranceCoverageItemRowId { get; set; }
        public Nullable<System.Guid> InsuranceCoverageItemHolderRowId { get; set; }
        public Nullable<decimal> AnnualAmountCovered { get; set; }
        public Nullable<decimal> MaximumQuantity { get; set; }
    }
}
