//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCoverageV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCoverageV()
        {
            this.InsuranceCoverageHolders = new HashSet<InsuranceCoverageHolder>();
            this.InvoiceClaims = new HashSet<InvoiceClaimV>();
        }
    
        public System.Guid RowId { get; set; }
        public System.Guid InsuranceProviderRowId { get; set; }
        public string PolicyNumber { get; set; }
        public System.DateTime CoverageStartDate { get; set; }
        public System.DateTime CoverageValidUntil { get; set; }
        public Nullable<bool> IsForAllListed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string PlanNumber { get; set; }
        public string DivisionNumber { get; set; }
        public string ID { get; set; }
        public string InsuranceCoverageYearType { get; set; }
        public Nullable<System.Guid> PolicyOwnerRowId { get; set; }
        public string PolicyOwnerFullName { get; set; }
    
        public virtual Patient PolicyOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageHolder> InsuranceCoverageHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimV> InvoiceClaims { get; set; }
    }
}
