//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCoverageHolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCoverageHolder()
        {
            this.InsuranceCoverageHolderServices = new HashSet<InsuranceCoverageHolderService>();
            this.InsuranceCoverageItemHolders = new HashSet<InsuranceCoverageItemHolder>();
        }
    
        public System.Guid RowId { get; set; }
        public System.Guid InsuranceCoverageRowId { get; set; }
        public System.Guid PolicyHolderRowId { get; set; }
        public string PolicyHolderType { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    
        public virtual InsuranceCoverage InsuranceCoverage { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageHolderService> InsuranceCoverageHolderServices { get; set; }
        public virtual InsuranceCoverageV InsuranceCoverageV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageItemHolder> InsuranceCoverageItemHolders { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
