//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryBalance
    {
        public System.Guid RowId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ItemType { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string Model { get; set; }
        public string Supplier { get; set; }
        public string Size { get; set; }
        public System.Guid CategoryRowId { get; set; }
        public string Factory { get; set; }
        public string Article { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string MeasurementUnit { get; set; }
        public string PrintLabel { get; set; }
        public bool UsePrintLabel { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
        public string TemplateFolder { get; set; }
    }
}
