//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryV
    {
        public System.Guid RowId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.Guid MedicalServiceOrSupplyRowId { get; set; }
        public Nullable<System.Guid> OrderItemRowId { get; set; }
        public Nullable<System.Guid> InvoiceItemRowId { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal Tax { get; set; }
        public decimal Credit { get; set; }
        public decimal Debit { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductItemType { get; set; }
        public string ProductNotes { get; set; }
        public Nullable<decimal> ProductUnitPrice { get; set; }
        public Nullable<decimal> ProductTaxRate { get; set; }
        public string ProductModel { get; set; }
        public string ProductSupplier { get; set; }
        public string ProductSize { get; set; }
        public Nullable<System.Guid> ProductCategoryRowId { get; set; }
        public string ProductFactory { get; set; }
        public string ProductArticle { get; set; }
        public Nullable<System.Guid> InvoiceRowId { get; set; }
        public Nullable<System.Guid> OrderRowId { get; set; }
        public Nullable<System.Guid> InvoicePatientRowId { get; set; }
        public string InvoicePatientName { get; set; }
        public Nullable<System.Guid> OrderSupplierRowId { get; set; }
        public string OrderSupplierName { get; set; }
    }
}
