//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceV()
        {
            this.InvoicePayments = new HashSet<InvoicePayment>();
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.InvoiceClaims = new HashSet<InvoiceClaimV>();
            this.InvoiceRefunds = new HashSet<InvoiceRefundV>();
        }
    
        public System.Guid RowId { get; set; }
        public System.Guid PatientRowId { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string BillTo { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToCity { get; set; }
        public string BillToProvince { get; set; }
        public string BillToPostCode { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> PaymentTax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> PaymentTotal { get; set; }
        public Nullable<decimal> PaymentRequest { get; set; }
        public string PatientFullName { get; set; }
        public string PrintTemplate { get; set; }
        public Nullable<System.Guid> ThirdPartyServiceProviderRowId { get; set; }
        public Nullable<System.Guid> Status1RowId { get; set; }
        public Nullable<System.Guid> Status2RowId { get; set; }
        public string ServiceProvidersList { get; set; }
        public string MedicalServicesList { get; set; }
        public string CategoriesList { get; set; }
        public Nullable<System.DateTime> MaxInvoiceItemDate { get; set; }
        public Nullable<System.DateTime> MinInvoiceItemDate { get; set; }
        public decimal Rate { get; set; }
        public Nullable<decimal> ApproveAmont { get; set; }
        public Nullable<decimal> DueByPatient { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public bool HasNoCoverage { get; set; }
        public Nullable<System.Guid> PatientReferrerRowId { get; set; }
        public Nullable<System.Guid> ServiceProviderRowId { get; set; }
        public Nullable<bool> HasCoordinationProblem { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        public virtual PatientV Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimV> InvoiceClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceRefundV> InvoiceRefunds { get; set; }
        public virtual InvoiceAdvinfoV InvoiceAdvinfo { get; set; }
    }
}
