//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceClaimDetail2InsurancePatientCategoryV
    {
        public Nullable<System.Guid> InsuranceCoverageRowId { get; set; }
        public System.Guid PatientRowId { get; set; }
        public System.Guid CategoryRowId { get; set; }
        public System.Guid InvoiceClaimDetailRowId { get; set; }
        public System.Guid InvoiceClaimRowId { get; set; }
        public System.Guid InvoiceRowId { get; set; }
        public Nullable<long> cnt { get; set; }
    }
}
