//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAdvinfoV
    {
        public System.Guid InvoiceRowId { get; set; }
        public string InsuranceProvidersInClaimsList { get; set; }
        public string PolicyOwnersInClaimsList { get; set; }
    }
}
