//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemV
    {
        public System.Guid RowId { get; set; }
        public System.Guid OrderRowId { get; set; }
        public System.Guid MedicalServiceOrSupplyRowId { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal Tax { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual OrderV Order { get; set; }
    }
}
