//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInsuranceCoverageView
    {
        public System.Guid PatientRowId { get; set; }
        public System.Guid InsuranceCoverageRowId { get; set; }
        public System.Guid InsuranceProviderRowId { get; set; }
        public string PolicyNumber { get; set; }
        public System.DateTime CoverageStartDate { get; set; }
        public System.DateTime CoverageValidUntil { get; set; }
    }
}
