//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsListView
    {
        public System.Guid RowId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Sex { get; set; }
        public string FamilyMemberType { get; set; }
        public System.Guid FamilyHeadRowId { get; set; }
        public string PrimaryPolicies { get; set; }
        public string SecondaryPolicies { get; set; }
        public string EmailAddress { get; set; }
        public string HomePhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string ReferrerName { get; set; }
        public byte[] Photo { get; set; }
        public string FamilyDoctor { get; set; }
        public Nullable<decimal> InvoiceFamilyBalance { get; set; }
        public decimal Rate { get; set; }
        public bool HasNoCoverage { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FamilyHeadLastName { get; set; }
        public bool IsNotRegistered { get; set; }
        public Nullable<int> spaCustomerNumber { get; set; }
    }
}
