//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    
    public partial class PayrollInfoResult
    {
        public System.Guid ServiceProviderRowId { get; set; }
        public string ServiceProviderFullName { get; set; }
        public decimal SumPaidByPatientsThisPeriod { get; set; }
        public decimal SumDueToDoctorThisPeriod { get; set; }
        public decimal SumDueToDoctorPrevPeriod { get; set; }
        public decimal SumPayrollPayThisPeriod { get; set; }
        public decimal SumPayrollPayPrevPeriod { get; set; }
        public decimal InvoicesTotal { get; set; }
        public decimal InvoicesApproveAmont { get; set; }
        public decimal InvoicesDueByPatient { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodFinish { get; set; }
        public string ServiceProviderType { get; set; }
        public string EmploymentType { get; set; }
    }
}
