//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefchargeV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefchargeV()
        {
            this.ChargeoutRefcharges = new HashSet<ChargeoutRefchargeV>();
            this.PaychargeRefcharges = new HashSet<PaychargeRefchargeV>();
        }
    
        public System.Guid RowId { get; set; }
        public Nullable<System.DateTime> PaychargeDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public string PaychargeType { get; set; }
        public string BankName { get; set; }
        public string ChequeNumber { get; set; }
        public string BrunchNumber { get; set; }
        public string TransitNumber { get; set; }
        public string AccountNumber { get; set; }
        public byte[] Image { get; set; }
        public string TransactionId { get; set; }
        public string RefchargeItemsType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string FullDescription { get; set; }
        public System.Guid ChargeoutRecipientRowId { get; set; }
        public string ChargeoutRecipientName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutRefchargeV> ChargeoutRefcharges { get; set; }
        public virtual ChargeoutRecipient ChargeoutRecipient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaychargeRefchargeV> PaychargeRefcharges { get; set; }
    }
}
