//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProviderService
    {
        public System.Guid RowId { get; set; }
        public System.Guid ServiceProviderRowId { get; set; }
        public System.Guid MedicalServiceOrSupplyRowId { get; set; }
        public decimal BasePrice { get; set; }
        public decimal BasePriceTaxRate { get; set; }
        public decimal HourlyRate { get; set; }
        public decimal HourlyRateTaxRate { get; set; }
        public string ChargeModel { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public decimal ChargeoutBasePrice { get; set; }
        public decimal ChargeoutBasePriceTaxRate { get; set; }
        public decimal ChargeoutHourlyRate { get; set; }
        public decimal ChargeoutHourlyRateTaxRate { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    
        public virtual MedicalServicesOrSupply MedicalServicesOrSupply { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ServiceProvider ServiceProvider1 { get; set; }
        public virtual ServiceProvider ServiceProvider2 { get; set; }
    }
}
