//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceProvider()
        {
            this.Appointments = new HashSet<AppointmentT>();
            this.ServiceProviderAssociations = new HashSet<ServiceProviderAssociation>();
            this.ServiceProviderServices = new HashSet<ServiceProviderService>();
            this.PayrollPayments = new HashSet<PayrollPaymentT>();
            this.Invoices = new HashSet<InvoiceT>();
            this.CalendarEvents = new HashSet<CalendarEventT>();
            this.SchedulerRecords = new HashSet<SchedulerRecord>();
            this.EmailSendRecipients = new HashSet<EmailSendRecipient>();
            this.Chargeouts = new HashSet<ChargeoutT>();
            this.EmailChargeRecipients = new HashSet<EmailChargeRecipient>();
            this.WorkInouts = new HashSet<WorkInout>();
            this.AppointmentBooks = new HashSet<AppointmentBook>();
            this.AppointmentBooks1 = new HashSet<AppointmentBook>();
            this.AppointmentClinicalNotes = new HashSet<AppointmentClinicalNote>();
            this.AppointmentClinicalNotes1 = new HashSet<AppointmentClinicalNote>();
            this.AppointmentInsuranceProviders = new HashSet<AppointmentInsuranceProvider>();
            this.AppointmentInsuranceProviders1 = new HashSet<AppointmentInsuranceProvider>();
            this.AppointmentRemainders = new HashSet<AppointmentRemainder>();
            this.AppointmentRemainders1 = new HashSet<AppointmentRemainder>();
            this.Appointments1 = new HashSet<AppointmentT>();
            this.Appointments2 = new HashSet<AppointmentT>();
            this.AppointmentStatuses = new HashSet<AppointmentStatus>();
            this.AppointmentStatuses1 = new HashSet<AppointmentStatus>();
            this.AppointmentTreatmentNotes = new HashSet<AppointmentTreatmentNote>();
            this.AppointmentTreatmentNotes1 = new HashSet<AppointmentTreatmentNote>();
            this.CalendarEvents1 = new HashSet<CalendarEventT>();
            this.CalendarEvents2 = new HashSet<CalendarEventT>();
            this.CalendarEventStatuses = new HashSet<CalendarEventStatus>();
            this.CalendarEventStatuses1 = new HashSet<CalendarEventStatus>();
            this.Categories = new HashSet<Category>();
            this.Categories1 = new HashSet<Category>();
            this.ChargeoutItems = new HashSet<ChargeoutItem>();
            this.ChargeoutItems1 = new HashSet<ChargeoutItem>();
            this.ChargeoutPaycharges = new HashSet<ChargeoutPaycharge>();
            this.ChargeoutPaycharges1 = new HashSet<ChargeoutPaycharge>();
            this.ChargeoutRecipients = new HashSet<ChargeoutRecipient>();
            this.ChargeoutRecipients1 = new HashSet<ChargeoutRecipient>();
            this.ChargeoutRefcharges = new HashSet<ChargeoutRefchargeT>();
            this.ChargeoutRefcharges1 = new HashSet<ChargeoutRefchargeT>();
            this.Chargeouts1 = new HashSet<ChargeoutT>();
            this.Chargeouts2 = new HashSet<ChargeoutT>();
            this.ChargeoutStatuses = new HashSet<ChargeoutStatus>();
            this.ChargeoutStatuses1 = new HashSet<ChargeoutStatus>();
            this.Cities = new HashSet<City>();
            this.Cities1 = new HashSet<City>();
            this.ClientErrors = new HashSet<ClientError>();
            this.ClientErrors1 = new HashSet<ClientError>();
            this.EmailChargeAttachments = new HashSet<EmailChargeAttachment>();
            this.EmailChargeAttachments1 = new HashSet<EmailChargeAttachment>();
            this.EmailChargeRecipients1 = new HashSet<EmailChargeRecipient>();
            this.EmailChargeRecipients2 = new HashSet<EmailChargeRecipient>();
            this.EmailCharges = new HashSet<EmailChargeT>();
            this.EmailCharges1 = new HashSet<EmailChargeT>();
            this.EmailSendAttachments = new HashSet<EmailSendAttachment>();
            this.EmailSendAttachments1 = new HashSet<EmailSendAttachment>();
            this.EmailSendRecipients1 = new HashSet<EmailSendRecipient>();
            this.EmailSendRecipients2 = new HashSet<EmailSendRecipient>();
            this.EmailSends = new HashSet<EmailSendT>();
            this.EmailSends1 = new HashSet<EmailSendT>();
            this.FormDocuments = new HashSet<FormDocument>();
            this.FormDocuments1 = new HashSet<FormDocument>();
            this.InsuranceCoverageHolders = new HashSet<InsuranceCoverageHolder>();
            this.InsuranceCoverageHolders1 = new HashSet<InsuranceCoverageHolder>();
            this.InsuranceCoverageHolderServices = new HashSet<InsuranceCoverageHolderService>();
            this.InsuranceCoverageHolderServices1 = new HashSet<InsuranceCoverageHolderService>();
            this.InsuranceCoverageItemCategories = new HashSet<InsuranceCoverageItemCategory>();
            this.InsuranceCoverageItemCategories1 = new HashSet<InsuranceCoverageItemCategory>();
            this.InsuranceCoverageItemHolders = new HashSet<InsuranceCoverageItemHolder>();
            this.InsuranceCoverageItemHolders1 = new HashSet<InsuranceCoverageItemHolder>();
            this.InsuranceCoverageItems = new HashSet<InsuranceCoverageItem>();
            this.InsuranceCoverageItems1 = new HashSet<InsuranceCoverageItem>();
            this.InsuranceCoverages = new HashSet<InsuranceCoverage>();
            this.InsuranceCoverages1 = new HashSet<InsuranceCoverage>();
            this.InsuranceCoverageServices = new HashSet<InsuranceCoverageService>();
            this.InsuranceCoverageServices1 = new HashSet<InsuranceCoverageService>();
            this.InsuranceProviders = new HashSet<InsuranceProvider>();
            this.InsuranceProviders1 = new HashSet<InsuranceProvider>();
            this.InsuranceProvidersViewGroupMappings = new HashSet<InsuranceProvidersViewGroupMapping>();
            this.InsuranceProvidersViewGroupMappings1 = new HashSet<InsuranceProvidersViewGroupMapping>();
            this.InsuranceProvidersViewGroups = new HashSet<InsuranceProvidersViewGroup>();
            this.InsuranceProvidersViewGroups1 = new HashSet<InsuranceProvidersViewGroup>();
            this.Inventories = new HashSet<InventoryT>();
            this.Inventories1 = new HashSet<InventoryT>();
            this.InvoiceClaimDetails = new HashSet<InvoiceClaimDetail>();
            this.InvoiceClaimDetails1 = new HashSet<InvoiceClaimDetail>();
            this.InvoiceClaims = new HashSet<InvoiceClaimT>();
            this.InvoiceClaims1 = new HashSet<InvoiceClaimT>();
            this.InvoiceClaimStatuses = new HashSet<InvoiceClaimStatus>();
            this.InvoiceClaimStatuses1 = new HashSet<InvoiceClaimStatus>();
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.InvoiceItems1 = new HashSet<InvoiceItem>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
            this.InvoicePayments1 = new HashSet<InvoicePayment>();
            this.InvoiceRefunds = new HashSet<InvoiceRefundT>();
            this.InvoiceRefunds1 = new HashSet<InvoiceRefundT>();
            this.Invoices1 = new HashSet<InvoiceT>();
            this.Invoices2 = new HashSet<InvoiceT>();
            this.InvoiceStatuses = new HashSet<InvoiceStatus>();
            this.InvoiceStatuses1 = new HashSet<InvoiceStatus>();
            this.MedicalConditions = new HashSet<MedicalCondition>();
            this.MedicalConditions1 = new HashSet<MedicalCondition>();
            this.MedicalHistoryRecords = new HashSet<MedicalHistoryRecordT>();
            this.MedicalHistoryRecords1 = new HashSet<MedicalHistoryRecordT>();
            this.MedicalServicesOrSupplies = new HashSet<MedicalServicesOrSupply>();
            this.MedicalServicesOrSupplies1 = new HashSet<MedicalServicesOrSupply>();
            this.OrderItems = new HashSet<OrderItemT>();
            this.OrderItems1 = new HashSet<OrderItemT>();
            this.OrderPayments = new HashSet<OrderPayment>();
            this.OrderPayments1 = new HashSet<OrderPayment>();
            this.Orders = new HashSet<OrderT>();
            this.Orders1 = new HashSet<OrderT>();
            this.PatientDocuments = new HashSet<PatientDocument>();
            this.PatientDocuments1 = new HashSet<PatientDocument>();
            this.PatientMedicalConditions = new HashSet<PatientMedicalCondition>();
            this.PatientMedicalConditions1 = new HashSet<PatientMedicalCondition>();
            this.PatientNotes = new HashSet<PatientNote>();
            this.PatientNotes1 = new HashSet<PatientNote>();
            this.PatientNoteStatuses = new HashSet<PatientNoteStatus>();
            this.PatientNoteStatuses1 = new HashSet<PatientNoteStatus>();
            this.PatientPhotos = new HashSet<PatientPhoto>();
            this.PatientPhotos1 = new HashSet<PatientPhoto>();
            this.Patients = new HashSet<Patient>();
            this.Patients1 = new HashSet<Patient>();
            this.PaychargeRefcharges = new HashSet<PaychargeRefchargeT>();
            this.PaychargeRefcharges1 = new HashSet<PaychargeRefchargeT>();
            this.Paycharges = new HashSet<PaychargeT>();
            this.Paycharges1 = new HashSet<PaychargeT>();
            this.PaymentRefunds = new HashSet<PaymentRefundT>();
            this.PaymentRefunds1 = new HashSet<PaymentRefundT>();
            this.Payments = new HashSet<PaymentT>();
            this.Payments1 = new HashSet<PaymentT>();
            this.PayrollPaymentAllocations = new HashSet<PayrollPaymentAllocationT>();
            this.PayrollPaymentAllocations1 = new HashSet<PayrollPaymentAllocationT>();
            this.PayrollPayments1 = new HashSet<PayrollPaymentT>();
            this.PayrollPayments2 = new HashSet<PayrollPaymentT>();
            this.PrintDocuments = new HashSet<PrintDocument>();
            this.PrintDocuments1 = new HashSet<PrintDocument>();
            this.ProfessionalAssociations = new HashSet<ProfessionalAssociation>();
            this.ProfessionalAssociations1 = new HashSet<ProfessionalAssociation>();
            this.PublicHolidays = new HashSet<PublicHoliday>();
            this.PublicHolidays1 = new HashSet<PublicHoliday>();
            this.Refcharges = new HashSet<RefchargeT>();
            this.Refcharges1 = new HashSet<RefchargeT>();
            this.Referrers = new HashSet<Referrer>();
            this.Referrers1 = new HashSet<Referrer>();
            this.Refunds = new HashSet<RefundT>();
            this.Refunds1 = new HashSet<RefundT>();
            this.SchedulerRecordItems = new HashSet<SchedulerRecordItem>();
            this.SchedulerRecordItems1 = new HashSet<SchedulerRecordItem>();
            this.SchedulerRecords1 = new HashSet<SchedulerRecord>();
            this.SchedulerRecords2 = new HashSet<SchedulerRecord>();
            this.ServiceProviderAssociations1 = new HashSet<ServiceProviderAssociation>();
            this.ServiceProviderAssociations2 = new HashSet<ServiceProviderAssociation>();
            this.ServiceProviders1 = new HashSet<ServiceProvider>();
            this.ServiceProviders11 = new HashSet<ServiceProvider>();
            this.ServiceProviderServices1 = new HashSet<ServiceProviderService>();
            this.ServiceProviderServices2 = new HashSet<ServiceProviderService>();
            this.SupplierPaymentRefunds = new HashSet<SupplierPaymentRefundT>();
            this.SupplierPaymentRefunds1 = new HashSet<SupplierPaymentRefundT>();
            this.SupplierPayments = new HashSet<SupplierPaymentT>();
            this.SupplierPayments1 = new HashSet<SupplierPaymentT>();
            this.SupplierRefunds = new HashSet<SupplierRefundT>();
            this.SupplierRefunds1 = new HashSet<SupplierRefundT>();
            this.Suppliers = new HashSet<Supplier>();
            this.Suppliers1 = new HashSet<Supplier>();
            this.Templates = new HashSet<Template>();
            this.Templates1 = new HashSet<Template>();
            this.ThirdPartyServiceProviders = new HashSet<ThirdPartyServiceProvider>();
            this.ThirdPartyServiceProviders1 = new HashSet<ThirdPartyServiceProvider>();
            this.TreatmentPlanRecords = new HashSet<TreatmentPlanRecordT>();
            this.TreatmentPlanRecords1 = new HashSet<TreatmentPlanRecordT>();
            this.UserSettings = new HashSet<UserSetting>();
            this.UserSettings1 = new HashSet<UserSetting>();
            this.WorkInouts1 = new HashSet<WorkInout>();
            this.WorkInouts2 = new HashSet<WorkInout>();
            this.LoginInouts = new HashSet<LoginInout>();
            this.LoginInouts1 = new HashSet<LoginInout>();
            this.LoginInouts2 = new HashSet<LoginInout>();
        }
    
        public System.Guid RowId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string AddressLine { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string PhoneNumber { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string Qualifications { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.Guid> AppointmentBookRowId { get; set; }
        public string AppointmentBackgroundColor { get; set; }
        public string AppointmentForegroundColor { get; set; }
        public string Position { get; set; }
        public string FooterText { get; set; }
        public string HeaderText { get; set; }
        public string FullName { get; set; }
        public decimal DoctorRate { get; set; }
        public string ServiceType { get; set; }
        public string EmploymentType { get; set; }
        public int MaximumDayAppointments { get; set; }
        public string C___WorkWee22kDays___ { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsOfficeEmployee { get; set; }
        public Nullable<System.Guid> RoleRowId { get; set; }
        public byte[] Signature { get; set; }
    
        public virtual AppointmentBook AppointmentBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentT> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderAssociation> ServiceProviderAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderService> ServiceProviderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPaymentT> PayrollPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceT> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarEventT> CalendarEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulerRecord> SchedulerRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendRecipient> EmailSendRecipients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutT> Chargeouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeRecipient> EmailChargeRecipients { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInout> WorkInouts { get; set; }
        public virtual User User11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentBook> AppointmentBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentBook> AppointmentBooks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentClinicalNote> AppointmentClinicalNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentClinicalNote> AppointmentClinicalNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentInsuranceProvider> AppointmentInsuranceProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentInsuranceProvider> AppointmentInsuranceProviders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentRemainder> AppointmentRemainders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentRemainder> AppointmentRemainders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentT> Appointments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentT> Appointments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentStatus> AppointmentStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentStatus> AppointmentStatuses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTreatmentNote> AppointmentTreatmentNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTreatmentNote> AppointmentTreatmentNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarEventT> CalendarEvents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarEventT> CalendarEvents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarEventStatus> CalendarEventStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarEventStatus> CalendarEventStatuses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutItem> ChargeoutItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutItem> ChargeoutItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutPaycharge> ChargeoutPaycharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutPaycharge> ChargeoutPaycharges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutRecipient> ChargeoutRecipients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutRecipient> ChargeoutRecipients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutRefchargeT> ChargeoutRefcharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutRefchargeT> ChargeoutRefcharges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutT> Chargeouts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutT> Chargeouts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutStatus> ChargeoutStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutStatus> ChargeoutStatuses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientError> ClientErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientError> ClientErrors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeAttachment> EmailChargeAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeAttachment> EmailChargeAttachments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeRecipient> EmailChargeRecipients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeRecipient> EmailChargeRecipients2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeT> EmailCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeT> EmailCharges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendAttachment> EmailSendAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendAttachment> EmailSendAttachments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendRecipient> EmailSendRecipients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendRecipient> EmailSendRecipients2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendT> EmailSends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendT> EmailSends1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDocument> FormDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDocument> FormDocuments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageHolder> InsuranceCoverageHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageHolder> InsuranceCoverageHolders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageHolderService> InsuranceCoverageHolderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageHolderService> InsuranceCoverageHolderServices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageItemCategory> InsuranceCoverageItemCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageItemCategory> InsuranceCoverageItemCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageItemHolder> InsuranceCoverageItemHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageItemHolder> InsuranceCoverageItemHolders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageItem> InsuranceCoverageItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageItem> InsuranceCoverageItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverage> InsuranceCoverages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverage> InsuranceCoverages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageService> InsuranceCoverageServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCoverageService> InsuranceCoverageServices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceProvider> InsuranceProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceProvider> InsuranceProviders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceProvidersViewGroupMapping> InsuranceProvidersViewGroupMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceProvidersViewGroupMapping> InsuranceProvidersViewGroupMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceProvidersViewGroup> InsuranceProvidersViewGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceProvidersViewGroup> InsuranceProvidersViewGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryT> Inventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryT> Inventories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimDetail> InvoiceClaimDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimDetail> InvoiceClaimDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimT> InvoiceClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimT> InvoiceClaims1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimStatus> InvoiceClaimStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceClaimStatus> InvoiceClaimStatuses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceRefundT> InvoiceRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceRefundT> InvoiceRefunds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceT> Invoices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceT> Invoices2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceStatus> InvoiceStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceStatus> InvoiceStatuses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalCondition> MedicalConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalCondition> MedicalConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistoryRecordT> MedicalHistoryRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistoryRecordT> MedicalHistoryRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalServicesOrSupply> MedicalServicesOrSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalServicesOrSupply> MedicalServicesOrSupplies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemT> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemT> OrderItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderT> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderT> Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDocument> PatientDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDocument> PatientDocuments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedicalCondition> PatientMedicalConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedicalCondition> PatientMedicalConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientNote> PatientNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientNote> PatientNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientNoteStatus> PatientNoteStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientNoteStatus> PatientNoteStatuses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientPhoto> PatientPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientPhoto> PatientPhotos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaychargeRefchargeT> PaychargeRefcharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaychargeRefchargeT> PaychargeRefcharges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaychargeT> Paycharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaychargeT> Paycharges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRefundT> PaymentRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRefundT> PaymentRefunds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentT> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentT> Payments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPaymentAllocationT> PayrollPaymentAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPaymentAllocationT> PayrollPaymentAllocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPaymentT> PayrollPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPaymentT> PayrollPayments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintDocument> PrintDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintDocument> PrintDocuments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessionalAssociation> ProfessionalAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessionalAssociation> ProfessionalAssociations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicHoliday> PublicHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicHoliday> PublicHolidays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefchargeT> Refcharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefchargeT> Refcharges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referrer> Referrers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referrer> Referrers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundT> Refunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundT> Refunds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulerRecordItem> SchedulerRecordItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulerRecordItem> SchedulerRecordItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulerRecord> SchedulerRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulerRecord> SchedulerRecords2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderAssociation> ServiceProviderAssociations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderAssociation> ServiceProviderAssociations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProvider> ServiceProviders1 { get; set; }
        public virtual ServiceProvider ServiceProvider1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProvider> ServiceProviders11 { get; set; }
        public virtual ServiceProvider ServiceProvider2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderService> ServiceProviderServices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderService> ServiceProviderServices2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPaymentRefundT> SupplierPaymentRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPaymentRefundT> SupplierPaymentRefunds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPaymentT> SupplierPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPaymentT> SupplierPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierRefundT> SupplierRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierRefundT> SupplierRefunds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Template> Templates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Template> Templates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThirdPartyServiceProvider> ThirdPartyServiceProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThirdPartyServiceProvider> ThirdPartyServiceProviders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentPlanRecordT> TreatmentPlanRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentPlanRecordT> TreatmentPlanRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSetting> UserSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSetting> UserSettings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInout> WorkInouts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInout> WorkInouts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginInout> LoginInouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginInout> LoginInouts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginInout> LoginInouts2 { get; set; }
    }
}
