//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProviderV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceProviderV()
        {
            this.ServiceProviderServices = new HashSet<ServiceProviderService>();
            this.ServiceProviderAssociations = new HashSet<ServiceProviderAssociation>();
        }
    
        public System.Guid RowId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string AddressLine { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string PhoneNumber { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string Qualifications { get; set; }
        public string EmailAddress { get; set; }
        public string AppointmentBackgroundColor { get; set; }
        public string AppointmentForegroundColor { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<System.Guid> AssociationRowId { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> RegistrationExpiryDate { get; set; }
        public string AssociationCode { get; set; }
        public string AssociationName { get; set; }
        public string AssosiationsList { get; set; }
        public string FooterText { get; set; }
        public string HeaderText { get; set; }
        public Nullable<System.Guid> AppointmentBookRowId { get; set; }
        public string Position { get; set; }
        public decimal DoctorRate { get; set; }
        public string FullName { get; set; }
        public string ServiceType { get; set; }
        public string EmploymentType { get; set; }
        public int MaximumDayAppointments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderService> ServiceProviderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderAssociation> ServiceProviderAssociations { get; set; }
    }
}
