//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceProvider()
        {
            this.Appointments = new HashSet<AppointmentT>();
            this.ServiceProviderAssociations = new HashSet<ServiceProviderAssociation>();
            this.ServiceProviderServices = new HashSet<ServiceProviderService>();
            this.PayrollPayments = new HashSet<PayrollPaymentT>();
            this.Invoices = new HashSet<InvoiceT>();
            this.CalendarEvents = new HashSet<CalendarEventT>();
            this.SchedulerRecords = new HashSet<SchedulerRecord>();
            this.EmailSendRecipients = new HashSet<EmailSendRecipient>();
            this.Chargeouts = new HashSet<ChargeoutT>();
            this.EmailChargeRecipients = new HashSet<EmailChargeRecipient>();
            this.WorkInouts = new HashSet<WorkInout>();
        }
    
        public System.Guid RowId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string AddressLine { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string PhoneNumber { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string Qualifications { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.Guid> AppointmentBookRowId { get; set; }
        public string AppointmentBackgroundColor { get; set; }
        public string AppointmentForegroundColor { get; set; }
        public string Position { get; set; }
        public string FooterText { get; set; }
        public string HeaderText { get; set; }
        public string FullName { get; set; }
        public decimal DoctorRate { get; set; }
        public string ServiceType { get; set; }
        public string EmploymentType { get; set; }
        public int MaximumDayAppointments { get; set; }
        public string C___WorkWee22kDays___ { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    
        public virtual AppointmentBook AppointmentBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentT> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderAssociation> ServiceProviderAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderService> ServiceProviderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPaymentT> PayrollPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceT> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarEventT> CalendarEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulerRecord> SchedulerRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSendRecipient> EmailSendRecipients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeoutT> Chargeouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailChargeRecipient> EmailChargeRecipients { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkInout> WorkInouts { get; set; }
    }
}
