//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profibiz.PracticeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProviderAssociation
    {
        public System.Guid RowId { get; set; }
        public System.Guid AssociationRowId { get; set; }
        public System.Guid ServiceProviderRowId { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> RegistrationExpiryDate { get; set; }
        public bool IsPrimary { get; set; }
        public Nullable<System.Guid> CreatedByUserRowId { get; set; }
        public Nullable<System.Guid> UpdatedByUserRowId { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedByDateTime { get; set; }
    
        public virtual ProfessionalAssociation ProfessionalAssociation { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
